import SiteLayout, { PageHero, SectionHeading, ActionLink, ContactCTA } from '@/components/SiteLayout';
import OfficeModules from '@/sections/OfficeModules';

export default function OfficeAIPage() {
  return <SiteLayout><PageHero eyebrow="OfficeAI / 国企办公解决方案" title="让企业技能成为每位员工的办公能力" description="TokenHub、SkillHub、Agent Admin 与 OfficeAgent 协同，将模型资源、业务技能与组织治理融入员工日常工作。"><div className="hero-actions"><ActionLink to="/support/sales?business=office">预约 OfficeAI 演示</ActionLink><ActionLink to="/cases" secondary>查看国企实践</ActionLink></div></PageHero>
    <section className="section-pad"><div className="site-shell"><SectionHeading eyebrow="产品组成" title="四个模块，各司其职" description="从底层资源到员工入口，以一套完整方案承接国企办公需求；各模块的交付与集成范围按项目约定。" /><OfficeModules detailed /></div></section>
    <section className="section-pad section-tint"><div className="site-shell"><SectionHeading eyebrow="协作流程" title="一次任务，如何走向可用结果" description="以办公材料准备为例：员工提出任务，调用企业技能与授权模型，形成可复核的成果，管理规则贯穿全过程。" /><div className="office-workflow"><div className="governance-bar"><strong>Agent Admin</strong><span>组织权限 · 智能体发布 · 运行审计</span></div><div className="four-grid">{[['OfficeAgent', '员工提出任务', '说明目标、提供资料，确认任务范围。'], ['SkillHub', '调用企业技能', '复用材料整理、制度检索等办公技能。'], ['TokenHub', '使用模型资源', '按授权与额度调用模型，记录用量。'], ['人工确认', '审核业务成果', '检查内容与依据，再进入后续业务流程。']].map(([label, title, desc], index) => <article key={label}><span className="step-number">0{index + 1}</span><p className="eyebrow">{label}</p><h3>{title}</h3><p>{desc}</p></article>)}</div></div></div></section>
    <section className="section-pad"><div className="site-shell"><SectionHeading eyebrow="办公应用场景" title="覆盖通用办公，延伸专业业务" description="按企业实际流程配置技能，逐项确定使用范围与验收口径。" /><div className="three-grid">{[['文档与材料', '辅助起草、整理、摘要与报告编制，让员工更快形成可复核的工作材料。'], ['制度与知识', '围绕企业制度、人事规则与业务知识，提供检索、问答与资料定位。'], ['专业业务辅助', '围绕合同审查、评标材料、审计准备等任务，配置专业规则与人工复核流程。']].map(([title, desc]) => <article className="content-card" key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
    <section className="section-pad section-tint"><div className="site-shell"><SectionHeading eyebrow="国企落地要求" title="使用便利，管理有序" /><div className="three-grid">{[['部署与数据边界', '结合企业环境评估私有化部署与系统集成，明确数据接入、存储和访问范围。'], ['组织与权限', '将模型、技能和智能体使用纳入企业组织权限，明确管理员与员工职责。'], ['结果与责任', 'AI 提供业务辅助，关键操作和专业结论由授权人员复核确认。']].map(([title, desc]) => <article className="content-card" key={title}><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section><ContactCTA /></SiteLayout>;
}
